#!/usr/bin/env node

const repository = process.env.GITHUB_REPOSITORY;
const token = process.env.GITHUB_TOKEN;

if (!repository || !token) {
  console.error("[ops-digest] Missing GITHUB_REPOSITORY or GITHUB_TOKEN.");
  process.exit(1);
}

const [owner, repo] = repository.split("/");
if (!owner || !repo) {
  console.error("[ops-digest] Invalid GITHUB_REPOSITORY format.");
  process.exit(1);
}

const dateKey = new Date().toISOString().slice(0, 10);
const title = `[OPS] Daily Digest ${dateKey}`;

const existing = await findIssueByTitle(owner, repo, token, title);
if (existing) {
  console.log(`[ops-digest] Digest already exists: ${existing.html_url}`);
  process.exit(0);
}

const [openIncidents, openInAppReports] = await Promise.all([
  countOpenIssues(owner, repo, token, "label:ops:incident state:open"),
  countOpenIssues(owner, repo, token, "label:source:in-app-report state:open"),
]);

const body = [
  "Automated daily operations digest.",
  "",
  `- Date (UTC): ${dateKey}`,
  `- Open incident issues: ${openIncidents}`,
  `- Open in-app report issues: ${openInAppReports}`,
  "",
  "### Checklist",
  "- [ ] Review failed deploys from last 24h",
  "- [ ] Review open incidents and assign owners",
  "- [ ] Verify user-facing critical paths",
  "",
  "### Notes",
  "Add any observed regressions or actions here.",
].join("\n");

const created = await createIssue(owner, repo, token, {
  title,
  body,
  labels: ["ops:autogenerated"],
});

console.log(`[ops-digest] Created ${created.html_url}`);

async function githubRequest(url, options = {}) {
  const response = await fetch(url, {
    ...options,
    headers: {
      authorization: `Bearer ${token}`,
      accept: "application/vnd.github+json",
      "content-type": "application/json",
      "user-agent": "realdrive-ops-bot/phase-1",
      ...(options.headers ?? {}),
    },
  });

  const payload = await safeJson(response);
  if (!response.ok) {
    throw new Error(`GitHub API ${response.status}: ${JSON.stringify(payload)}`);
  }

  return payload;
}

async function findIssueByTitle(ownerName, repoName, authToken, issueTitle) {
  void authToken;
  const query = encodeURIComponent(`repo:${ownerName}/${repoName} in:title type:issue \"${issueTitle}\"`);
  const result = await githubRequest(`https://api.github.com/search/issues?q=${query}&per_page=5`);
  return result.items?.find((item) => item.title === issueTitle) ?? null;
}

async function countOpenIssues(ownerName, repoName, authToken, extraQuery) {
  void authToken;
  const query = encodeURIComponent(`repo:${ownerName}/${repoName} is:issue ${extraQuery}`);
  const result = await githubRequest(`https://api.github.com/search/issues?q=${query}&per_page=1`);
  return result.total_count ?? 0;
}

async function createIssue(ownerName, repoName, authToken, payload) {
  void authToken;
  return githubRequest(`https://api.github.com/repos/${ownerName}/${repoName}/issues`, {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

async function safeJson(response) {
  try {
    return await response.json();
  } catch {
    return null;
  }
}
