#!/usr/bin/env node

const DEFAULT_TIMEOUT_MS = Number.parseInt(process.env.OPS_TIMEOUT_MS ?? "10000", 10);
const CREATE_ISSUE_ON_FAILURE = (process.env.OPS_CREATE_ISSUE_ON_FAILURE ?? "true").toLowerCase() === "true";
const MAX_LATENCY_MS = Number.parseInt(process.env.OPS_MAX_LATENCY_MS ?? "0", 10);
const endpointList = parseEndpointList(process.env.OPS_HEALTH_ENDPOINTS ?? "");

if (endpointList.length === 0) {
  console.error("[ops-health] No endpoints configured. Set OPS_HEALTH_ENDPOINTS as a comma-separated list of URLs.");
  process.exit(1);
}

const runAt = new Date().toISOString();
const results = [];

for (const url of endpointList) {
  results.push(await checkEndpoint(url, DEFAULT_TIMEOUT_MS));
}

const failed = results.filter((item) => item.ok === false);
const summary = {
  runAt,
  total: results.length,
  passed: results.length - failed.length,
  failed: failed.length,
  results,
};

console.log(JSON.stringify(summary, null, 2));

if (failed.length > 0 && CREATE_ISSUE_ON_FAILURE) {
  await maybeCreateIncidentIssue(summary);
}

process.exit(failed.length > 0 ? 1 : 0);

async function checkEndpoint(url, timeoutMs) {
  const started = Date.now();
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const response = await fetch(url, {
      method: "GET",
      headers: {
        "user-agent": "realdrive-ops-bot/phase-1",
      },
      signal: controller.signal,
    });

    const elapsedMs = Date.now() - started;
    const statusOk = response.status >= 200 && response.status < 300;
    const latencyOk = MAX_LATENCY_MS <= 0 ? true : elapsedMs <= MAX_LATENCY_MS;
    const ok = statusOk && latencyOk;

    return {
      url,
      ok,
      status: response.status,
      elapsedMs,
      error: !statusOk ? `unexpected_status_${response.status}` : !latencyOk ? `latency_exceeded_${MAX_LATENCY_MS}ms` : null,
    };
  } catch (error) {
    const elapsedMs = Date.now() - started;
    return {
      url,
      ok: false,
      status: null,
      elapsedMs,
      error: error instanceof Error ? error.message : String(error),
    };
  } finally {
    clearTimeout(timer);
  }
}

function parseEndpointList(raw) {
  return raw
    .split(",")
    .map((value) => value.trim())
    .filter((value) => value.length > 0);
}

async function maybeCreateIncidentIssue(summary) {
  const token = process.env.GITHUB_TOKEN;
  const repository = process.env.GITHUB_REPOSITORY;

  if (!token || !repository) {
    console.warn("[ops-health] Skipped incident issue creation (missing GITHUB_TOKEN or GITHUB_REPOSITORY).");
    return;
  }

  const [owner, repo] = repository.split("/");
  if (!owner || !repo) {
    console.warn("[ops-health] Skipped incident issue creation (invalid GITHUB_REPOSITORY format).");
    return;
  }

  const failedEndpoints = summary.results.filter((entry) => entry.ok === false);
  const fingerprint = failedEndpoints
    .map((entry) => `${entry.url}|${entry.status ?? "ERR"}|${entry.error ?? "unknown"}`)
    .sort()
    .join(";");

  const today = new Date().toISOString().slice(0, 10);
  const issueTitle = `[OPS] Incident ${today}: ${failedEndpoints.length} endpoint(s) failing`;
  const issueBody = [
    "Automated health-check detected runtime failures.",
    "",
    `- Run at: ${summary.runAt}`,
    `- Failed checks: ${summary.failed}/${summary.total}`,
    `- Fingerprint: ${fingerprint}`,
    "",
    "### Failed endpoints",
    ...failedEndpoints.map(
      (entry) =>
        `- ${entry.url} | status=${entry.status ?? "n/a"} | latency=${entry.elapsedMs}ms | error=${entry.error ?? "none"}`,
    ),
    "",
    "### Next actions",
    "1) Validate deploy status (Vercel/Render)",
    "2) Check API logs, latency, and recent releases",
    "3) Add resolution notes and close this issue",
  ].join("\n");

  const labels = ["ops:incident", "ops:autogenerated", "source:health-check"];

  try {
    const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
      method: "POST",
      headers: {
        authorization: `Bearer ${token}`,
        accept: "application/vnd.github+json",
        "content-type": "application/json",
        "user-agent": "realdrive-ops-bot/phase-1",
      },
      body: JSON.stringify({
        title: issueTitle,
        body: issueBody,
        labels,
      }),
    });

    if (!response.ok) {
      const payload = await safeJson(response);
      console.warn(`[ops-health] Failed to create incident issue: ${response.status} ${JSON.stringify(payload)}`);
      return;
    }

    const created = await safeJson(response);
    console.log(`[ops-health] Created incident issue #${created.number}: ${created.html_url}`);
  } catch (error) {
    console.warn(`[ops-health] Incident issue creation failed: ${error instanceof Error ? error.message : String(error)}`);
  }
}

async function safeJson(response) {
  try {
    return await response.json();
  } catch {
    return null;
  }
}
