#!/usr/bin/env node
/**
 * scripts/ops/setup-labels.mjs
 * Creates all required GitHub labels for the RealDrive ops bot and feature review process.
 * Run: node scripts/ops/setup-labels.mjs
 * Requires: GITHUB_TOKEN and GITHUB_REPO in environment.
 */

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_REPO  = process.env.GITHUB_REPO;  // e.g. "bitquan/realdrive"

if (!GITHUB_TOKEN || !GITHUB_REPO) {
  console.error('❌  GITHUB_TOKEN and GITHUB_REPO are required.');
  process.exit(1);
}

const [owner, repo] = GITHUB_REPO.split('/');

const LABELS = [
  // ── Feature review ──────────────────────────────────────────────────
  { name: 'feature:request',     color: '0075ca', description: 'Community feature request' },
  { name: 'triage:looks-good',   color: '0e8a16', description: 'AI triage: aligned with platform policy' },
  { name: 'triage:needs-review', color: 'e4e669', description: 'AI triage: needs human review' },
  { name: 'triage:flagged',      color: 'd93f0b', description: 'AI triage: policy violation or abuse risk detected' },
  { name: 'status:approved',     color: '0e8a16', description: 'Feature approved by owner' },
  { name: 'status:rejected',     color: 'd93f0b', description: 'Feature rejected — not aligned with platform' },
  { name: 'roadmap:index',       color: '1d76db', description: 'Marks the public roadmap tracking issue' },

  // ── Ops bot ─────────────────────────────────────────────────────────
  { name: 'ops:incident',        color: 'd93f0b', description: 'Active production incident' },
  { name: 'ops:degraded',        color: 'e4e669', description: 'Partial service degradation' },
  { name: 'ops:autogenerated',   color: 'ededed', description: 'Created automatically by the ops bot' },
  { name: 'source:health-check', color: 'c2e0c6', description: 'Opened by the health-check workflow' },
  { name: 'source:in-app-report',color: 'c2e0c6', description: 'Submitted through the in-app report form' },
  { name: 'source:daily-digest', color: 'c2e0c6', description: 'Created by the daily ops digest' },
];

async function ghFetch(path, method, body) {
  const res = await fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      'Content-Type': 'application/json',
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  return { status: res.status, body: await res.json() };
}

let created = 0;
let updated = 0;
let failed  = 0;

for (const label of LABELS) {
  // Try to create — if 422 (already exists) update it instead
  const create = await ghFetch(`/repos/${owner}/${repo}/labels`, 'POST', label);

  if (create.status === 201) {
    console.log(`  ✅  created   ${label.name}`);
    created++;
  } else if (create.status === 422) {
    // Label exists — update color/description
    const update = await ghFetch(`/repos/${owner}/${repo}/labels/${encodeURIComponent(label.name)}`, 'PATCH', {
      color: label.color,
      description: label.description,
    });
    if (update.status === 200) {
      console.log(`  🔄  updated   ${label.name}`);
      updated++;
    } else {
      console.error(`  ❌  failed    ${label.name} — ${JSON.stringify(update.body)}`);
      failed++;
    }
  } else {
    console.error(`  ❌  failed    ${label.name} — status ${create.status}`);
    failed++;
  }
}

console.log('');
console.log(`Done — ${created} created, ${updated} updated, ${failed} failed.`);
if (failed > 0) process.exit(1);
